### ISSUE TITLE
Working with Nuxtjs and vue-apollo nuxt module

### ISSUE THREAD

**Issue by binaryweavers** [enzonotario/lighthouse-laravel-websockets#1]
@enzonotario first of all really appreciable as you spare time to help us with this. I am working with nuxtjs ad tried to set it up with nuxtjs using [nuxt-apollo](https://github.com/nuxt-community/apollo-module) module. 
I have setup [echo.link.js](https://github.com/enzonotario/lighthouse-laravel-websockets/blob/master/resources/js/echo.link.js) as it is and then in apollo client config (in dedicated file) I have combined the `echoLink` using `ApolloLink.from()` method
I am geting error
`Unexpected token export`
I played around with [echo.link.js](https://github.com/enzonotario/lighthouse-laravel-websockets/blob/master/resources/js/echo.link.js) and changed 
`import Echo from 'laravel-echo/dist/echo';`
 to 
import Echo from 'laravel-echo';
then error changes to 
`Pusher is not defined` 
I have installed pusher via npm too.
Can you please help me with that
again have no words to say thanks for such a favor

**Comment by enzonotario** [comment]
You're welcome!

I think you're missing to include the Pusher script: https://github.com/enzonotario/lighthouse-laravel-websockets/blob/d4433737f40ac3f307bccd314472d8bc6190cc51/resources/views/app.blade.php#L8

**Comment by binaryweavers** [comment]
> You're welcome!
> 
> I think you're missing to include the Pusher script:
> 
> https://github.com/enzonotario/lighthouse-laravel-websockets/blob/d4433737f40ac3f307bccd314472d8bc6190cc51/resources/views/app.blade.php#L8

My bad, I thought installing it via npm would be enough. Thanks for that it seems working now. I have attached `Pusher` to `windows` object using a nuxt plugin and it loaded with no errors and connection got established too.
Thank you once again <3
