### ISSUE TITLE
Warning, this example removes _all_ subscriptions when closing a single connection

### ISSUE THREAD

**Issue by stayallive** [enzonotario/lighthouse-laravel-websockets#17]
Hi There,

I am here because of this issue: https://github.com/nuwave/lighthouse/issues/1796.

Your code added to the `ArrayChannelManager` removes _all_ subscriptions connection to the websocket server each time a connection is removed from all channels.

https://github.com/enzonotario/lighthouse-laravel-websockets/blob/222531f198a4722ad9928f39aa7e96474071b6d9/app/WebSockets/Channels/ChannelManager/ArrayChannelManager.php#L16-L19

This also removes subscription for other connections, so this code only works if you have a single connection connected, but as you add more connections every time one of them disconnects it will remove _all_ subscriptions.

Might I suggest you update the example with some of the new ideas from here: https://github.com/nuwave/lighthouse/issues/847#issuecomment-618254044?

This way when people use your example they won't have a broken setup like the author of the issue I mentioned earlier.

Thanks for creating it in the first place, a lot of people have a hard time getting it working and we are working towards official support in Lighthouse but until that time I'd appreciate it if you could update!

**Comment by enzonotario** [comment]
Hi! Yes, my bad about that line. I have updated the example in #18. I have tested it and so far it works fine!

Thanks so much and is great to hear that it helps to others! Greetings!
