### ISSUE TITLE
Getting error on first serve sample

### ISSUE THREAD

**Issue by pishguy** [enzonotario/lighthouse-laravel-websockets#30]
after running `composer-update` and install `redis`, in first serve the application i get this error on console:

```
GraphQL execution errors for subscription 'subscribed'


Object { debugMessage: "Connection refused", message: "Internal server error", extensions: {…}, locations: (1) […], path: (1) […], trace: (63) […] }
​
debugMessage: "Connection refused"
​
extensions: Object { category: "internal" }
​
locations: Array [ {…} ]
​
message: "Internal server error"
​
path: Array [ "test" ]
​
trace: Array(63) [ {…}, {…}, {…}, … ]
​
<prototype>: Object { … }
```

how can i resolve this problem? thanks in advance

**Comment by enzonotario** [comment]
Hi there! It's just an example that works with `laravel-websockets`. So, to get it working, you should:

1. Run `composer install`
2. Edit your `.env` and set variables like:
```
PUSHER_APP_ID=test
PUSHER_APP_KEY=c6f11bf7ef7a4a283091
PUSHER_APP_SECRET=test
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

LIGHTHOUSE_CACHE_ENABLE=false
LIGHTHOUSE_QUEUE_BROADCASTS=false
LIGHTHOUSE_SUBSCRIPTION_STORAGE=file
```
3. Run `php artisan serve` and `php artisan websockets:serve`
4. Try it on http://localhost:8000

Please try with those steps. If you need more help, just comment in this issue.
